In [2]:
import numpy as np
# numpy 提供多维数组对象 其核心是 ndarray 对象

a = np.arange(15).reshape(3, 5)
print(a)

# 对象属性是:
# (1) ndim 轴
print(f'ndim轴：{a.ndim}')

# (2) shape 维度
print(f'shape数组维度：{a.shape}')

# (3) size 元素总数
print(f'size数组元素总数：{a.size}')

# (4) dtype 描述数组中元素类型的对象
print(f'dtype数组中元素类型：{a.dtype.name}')

# (5) itemsize 每个元素的字节大小
print(f'itemsize数组中元素字节大小：{a.itemsize}')

# (6) data 该缓冲区包含数组的实际元素
print(f'data数组中的实际元素：{a.data}')

type(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
ndim轴：2
shape数组维度：(3, 5)
size数组元素总数：15
dtype数组中元素类型：int32
itemsize数组中元素字节大小：4
data数组中的实际元素：<memory at 0x000001FB7161F520>


numpy.ndarray

In [2]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [3]:
c = np.array([[1, 2], [3, 4] ], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [4]:
np.zeros((3, 4))
np.ones((2,3,4), dtype=np.int16)
np.empty((2,3))

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [6]:
np.arange(10, 30, 5)
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [3]:
from numpy import pi
f = np.linspace(0, 2, 9)
k = np.linspace(0, 2*pi, 100)
l = np.sin(k)
print(l)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [8]:
# 打印数组
# a.最后一个轴从左到右打印
# b.倒数第二个从上到下打印
# c.其余部分也从上到下打印
# 每个切片用空行分隔
o = np.arange(24).reshape(2, 3, 4)
print(o)

p = np.arange(10000).reshape(100, 100)
print(p)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [14]:
# numpy 基本操作
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [15]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [16]:
A@B

array([[5, 4],
       [3, 4]])

In [17]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [19]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
b += a
print(b)

array([[3.55355573, 3.29424112, 3.83608004],
       [3.56650994, 3.05079072, 3.96449315]])

In [21]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print(b.dtype.name)
c = a+b
print(c)
print(c.dtype.name)
print(np.exp(c*1j))

float64
[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


In [9]:
d = np.random.random((2,3))
print(d)
print(d.sum())
print(d.min())
print(d.max())

[[0.23024219 0.28521947 0.80458303]
 [0.75860562 0.22832878 0.40140353]]
2.7083826122831294
0.22832878233851217
0.8045830294229788


In [10]:
g = np.arange(12).reshape(3,4)
print(g)
print(g.sum(axis=0))
print(g.min(axis=1))
print(g.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [12]:
# 通函数 sin cos exp
B = np.arange(3)
print(B)
C = np.exp(B)
D = np.sqrt(B)
F = np.array([2, -1., 4.])
print(np.add(B, C))

[0 1 2]
[1.         3.71828183 9.3890561 ]


In [8]:
# 索引 切片 迭代
a = np.arange(10) ** 3
print(a)
print(a[2])
print(a[2:5])
a[:6:2] = -1000
print(a)
print(a[::-1])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


<ipython-input-8-948bde753929>:10: RuntimeWarning: invalid value encountered in power
  print(i**(1/3.))


In [13]:
def func(x, y):
    return 10*x+y

b = np.fromfunction(func,(5,4),dtype=int)
print(b)
print(b[0:5,1])
print(b[1:3,:])
print(b[-1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


In [15]:
for i in b:
    print(i)
# 如果想要对数组中的每个元素执行操作可以使用flat属性
# 该属性是数组的所有元素的迭代器
for element in b.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [20]:
p = np.floor(10*np.random.random((3,4)))
print(p)
print(p.shape)
print(p.ravel())
print(p.reshape(6,2))
print(p.T)

[[9. 1. 7. 6.]
 [3. 2. 0. 4.]
 [8. 3. 2. 5.]]
(3, 4)
[9. 1. 7. 6. 3. 2. 0. 4. 8. 3. 2. 5.]
[[9. 1.]
 [7. 6.]
 [3. 2.]
 [0. 4.]
 [8. 3.]
 [2. 5.]]
[[9. 3. 8.]
 [1. 2. 3.]
 [7. 0. 2.]
 [6. 4. 5.]]


In [22]:
p.resize((2,6))
print(p)
# 如果在 reshape 操作中将 size 指定为-1则会自动计算其他的 size 大小
print(p.reshape(3,-1))

[[9. 1. 7. 6. 3. 2.]
 [0. 4. 8. 3. 2. 5.]]
[[9. 1. 7. 6.]
 [3. 2. 0. 4.]
 [8. 3. 2. 5.]]


In [25]:
# 几个数组可以沿不同的轴堆叠在一起
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a, b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0. 1.]
 [8. 6.]] [[2. 9.]
 [1. 7.]]
[[0. 1.]
 [8. 6.]
 [2. 9.]
 [1. 7.]]
[[0. 1. 2. 9.]
 [8. 6. 1. 7.]]


In [27]:
from numpy import newaxis
c = np.column_stack((a,b))
print(c)
a = np.array([4.,2.])
b = np.array([3.,8.])
c = np.column_stack((a,b))     # returns a 2D array
print(c)
print(np.hstack((a,b)))           # the result is different
print(a[:,newaxis])
print(np.column_stack((a[:,newaxis],b[:,newaxis])))
print(np.hstack((a[:,newaxis],b[:,newaxis])))

[[0. 1. 2. 9.]
 [8. 6. 1. 7.]]
[[4. 3.]
 [2. 8.]]
[4. 2. 3. 8.]
[[4.]
 [2.]]
[[4. 3.]
 [2. 8.]]
[[4. 3.]
 [2. 8.]]


In [28]:
t = np.r_[1:4,0,4]
print(t)

[1 2 3 0 4]


In [32]:
i = np.floor(10*np.random.random([2,12]))
print(i)
print(np.hsplit(i,3))
print(np.hsplit(i,(3,4)))

[[4. 5. 2. 3. 9. 2. 0. 4. 6. 3. 1. 9.]
 [7. 5. 4. 2. 9. 4. 0. 0. 9. 0. 0. 5.]]
[array([[4., 5., 2., 3.],
       [7., 5., 4., 2.]]), array([[9., 2., 0., 4.],
       [9., 4., 0., 0.]]), array([[6., 3., 1., 9.],
       [9., 0., 0., 5.]])]
[array([[4., 5., 2.],
       [7., 5., 4.]]), array([[3.],
       [2.]]), array([[9., 2., 0., 4., 6., 3., 1., 9.],
       [9., 4., 0., 0., 9., 0., 0., 5.]])]


In [43]:
# Python将可变对象作为引用传递 因此函数调用不会复制
a = np.arange(12)
a.shape = 3,4
b = a
print(b is a)

True


In [45]:
# 视图或浅拷贝
c = a.view()
# 创建一个相同数据的新数组
print(c is a, c.base is a)
c.shape = 2,6
c[0, 4] = 1234
print(a.shape)
print(a, c)

False True
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]] [[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]


In [46]:
# 切片数组会返回一个视图
s = a[:,1:3]
s[:] = 10
print(a)


[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [49]:
# 该copy方法生成数组及其数据的完整副本
d = a.copy()
print(d is a, d.base is a)

False False
