In [1]:
import numpy as np
import pandas as pd

# 生成对象
k = pd.Series([1,4,2,5,7,np.nan,2])
print(k)

0    1.0
1    4.0
2    2.0
3    5.0
4    7.0
5    NaN
6    2.0
dtype: float64


In [5]:
dates = pd.date_range('20201001', periods=6)
print(dates)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

DatetimeIndex(['2020-10-01', '2020-10-02', '2020-10-03', '2020-10-04',
               '2020-10-05', '2020-10-06'],
              dtype='datetime64[ns]', freq='D')


A         B         C         D
2020-10-01 -0.102714  0.323031 -0.378437 -0.725649
2020-10-02 -1.066629  1.250774 -0.517735  0.353463
2020-10-03 -1.233580  1.518897 -2.303529  0.953673
2020-10-04 -0.158637 -0.237787  0.109893  0.347391
2020-10-05 -0.355548  0.102544  0.456307  1.244511
2020-10-06 -0.798325  1.169551 -1.120230  1.737584

In [6]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [7]:
df2.dtypes


A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [12]:
df.head()
df.tail(2)
print(df.index)
print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')

In [13]:
print(df.to_numpy())
print(df2.to_numpy())


[[-0.10271358  0.32303054 -0.37843705 -0.72564868]
 [-1.0666289   1.2507744  -0.51773468  0.35346255]
 [-1.23357959  1.51889707 -2.30352905  0.95367296]
 [-0.15863676 -0.23778748  0.10989268  0.34739073]
 [-0.3555481   0.10254443  0.45630671  1.24451127]
 [-0.79832497  1.16955128 -1.12022989  1.73758357]]
[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']]


In [14]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.619239  0.687835 -0.625622  0.651829
std    0.481275  0.717222  0.984307  0.860278
min   -1.233580 -0.237787 -2.303529 -0.725649
25%   -0.999553  0.157666 -0.969606  0.348909
50%   -0.576937  0.746291 -0.448086  0.653568
75%   -0.207865  1.230469 -0.012190  1.171802
max   -0.102714  1.518897  0.456307  1.737584

In [15]:
df.T

2020-10-01  2020-10-02  2020-10-03  2020-10-04  2020-10-05  2020-10-06
A   -0.102714   -1.066629   -1.233580   -0.158637   -0.355548   -0.798325
B    0.323031    1.250774    1.518897   -0.237787    0.102544    1.169551
C   -0.378437   -0.517735   -2.303529    0.109893    0.456307   -1.120230
D   -0.725649    0.353463    0.953673    0.347391    1.244511    1.737584

In [16]:
# 按轴排序
df.sort_index(axis=1, ascending=False)

D         C         B         A
2020-10-01 -0.725649 -0.378437  0.323031 -0.102714
2020-10-02  0.353463 -0.517735  1.250774 -1.066629
2020-10-03  0.953673 -2.303529  1.518897 -1.233580
2020-10-04  0.347391  0.109893 -0.237787 -0.158637
2020-10-05  1.244511  0.456307  0.102544 -0.355548
2020-10-06  1.737584 -1.120230  1.169551 -0.798325

In [17]:
# 按值排序
df.sort_values(by='B')

A         B         C         D
2020-10-04 -0.158637 -0.237787  0.109893  0.347391
2020-10-05 -0.355548  0.102544  0.456307  1.244511
2020-10-01 -0.102714  0.323031 -0.378437 -0.725649
2020-10-06 -0.798325  1.169551 -1.120230  1.737584
2020-10-02 -1.066629  1.250774 -0.517735  0.353463
2020-10-03 -1.233580  1.518897 -2.303529  0.953673