In [1]:
# 提供灵活和速度的深度学习研究平台
import torch

x = torch.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [2]:
y = torch.rand(5, 3)
y

tensor([[0.9429, 0.2885, 0.0140],
        [0.5817, 0.7775, 0.6856],
        [0.5864, 0.2801, 0.0860],
        [0.0336, 0.9517, 0.7734],
        [0.0045, 0.3630, 0.3196]])

In [3]:
z = torch.zeros(5, 3, dtype=torch.long)
z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
i = torch.tensor([5.5, 3])
i

tensor([5.5000, 3.0000])

In [6]:
j = i.new_ones(5, 3, dtype=torch.double)
j

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
k = torch.randn_like(x, dtype=torch.float)
k

tensor([[-0.3389,  0.1564,  0.2292],
        [-1.1980,  1.0576,  0.4679],
        [ 0.3235,  0.6186, -1.5368],
        [-0.0277, -2.2316,  0.2277],
        [-0.1909, -1.0587, -1.2633]])

In [9]:
print(k.size())

torch.Size([5, 3])
